# Backtest configs for a custom demand dataset
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 1
  num_rolls: 510
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 7
  num_rolls: 504
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 14
  num_rolls: 497
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 30
  num_rolls: 481
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 60
  num_rolls: 451
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 180
  num_rolls: 331
  distance: 1
- name: demand_data_all_cleaned_daily.csv
  hf_repo: data/
  offset: 511
  prediction_length: 365
  num_rolls: 146
  distance: 1