# Backtest configs for a custom demand dataset
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 1
  num_rolls: 656
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 7
  num_rolls: 650
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 14
  num_rolls: 643
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 30
  num_rolls: 627
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 60
  num_rolls: 597
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 180
  num_rolls: 477
  distance: 1
- name: demand_data_all_nsw_daily.csv
  hf_repo: data/
  offset: 657
  prediction_length: 365
  num_rolls: 292
  distance: 1